server_tokens	off;

server {
	listen		80;
	server_name	_;
	root		/var/www/html;

	location / {
		root	/var/www/html;
		index	index.php index.html index.htm;
		add_header Supports-Loading-Mode credentialed-prerender;
		
		#return 302 https://depth.lab-ish.com/;
	}

	#error_page	400 401 402 403 404	/40x.html;
	#error_page	500 502 503 504		/50x.html;
	#location = /50x.html {
	#	root   /usr/share/nginx/html;
	#}
}
